df_cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart, name='ucart'),
    url(r'^add/(\d+)_(\d+)/$', views.add, name='add'),
    url(r'^delete/(\d+)/$', views.delete_good, name='delete'),
]

df_goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^list/(?P<id>\d+)/$', views.list_item, name='list'),
	url(r'^listHandle/$', views.list_items, name='lists'),
	url(r'^commodity/(?P<id>\d+)/$', views.commodity, name='commodity'),
	# url(r'^logging/$', views.logging),
]

df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^register/$', views.register, name='register'),
	url(r'^register_handle/$', views.register_handle, name='register_handle'),
	url(r'^register_exist/$', views.register_exist, name='register_exist'),
	url(r'^login/$', views.login, name='login'),
	url(r'^site/$', views.site, name='site'),
	url(r'^logout$', views.logout, name='logout'),
	# url(r'^logging/$', views.logging),
]

eshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('df_user.urls', namespace='user')),
    url(r'^', include('df_goods.urls', namespace='goods')),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),
]

df_cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class CartInfo(models.Model):
	user = models.ForeignKey('df_user.UserInfo')
	goods = models.ForeignKey('df_goods.GoodsInfo')
	count = models.IntegerField()

df_goods/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from tinymce.models import HTMLField
# Create your models here.

class TypeInfo(models.Model):
	ttype = models.CharField(max_length=20)
	isDelete = models.BooleanField(default=False)

class GoodsInfo(models.Model):
	gtitle = models.CharField(max_length=200)
	gpic = models.ImageField(upload_to='df_goods')
	gprice = models.DecimalField(max_digits=10, decimal_places=2)
	isDelete = models.BooleanField(default=False)
	gstorage = models.IntegerField()
	gcontent = HTMLField()
	gtype = models.ForeignKey(TypeInfo)

df_user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class UserInfo(models.Model):
	uname = models.CharField(max_length=20)
	upwd = models.CharField(max_length=40)
	uemail = models.CharField(max_length=30)
	uperson = models.CharField(max_length=20, default='')
	ureceiver = models.CharField(max_length=100, default='')
	uzip = models.CharField(max_length=6, default='')
	uphone = models.CharField(max_length=11, default='')

df_cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

from models import CartInfo
from df_user.check_login import check_login
# Create your views here.

@check_login
def cart(request):
	uid = request.session['uname']
	carts = CartInfo.objects.filter(user_id=uid)
	context = {
		'title':'购物车',
		'carts':carts,
	}

	return render(request, 'df_cart/cart.html', context)

@check_login
def add(request, goods_id, count):
	uid = request.session['uname']
	goods_id = int(goods_id)
	count = int(count)

	carts = CartInfo.objects.filter(goods_id=goods_id, user_id=uid)

	# return HttpResponse(carts[0].id)
	if len(carts)>=1:
		cart = carts[0]
		cart.count = cart.count + count

	else:
		cart = CartInfo()
		cart.user_id = uid
		cart.goods_id = goods_id
		cart.count = count

	cart.save()

	if request.is_ajax():
		return JsonResponse({'count':cart.count})

	return redirect('/cart/')

@check_login
def delete_good(request, cart_id):
	try:
		good = CartInfo.objects.filter(id=int(cart_id))
		good.delete()
		context = {'result':1}
	except:
		context = {'result':0}
	return JsonResponse(context)

df_goods/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from models import GoodsInfo, TypeInfo
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.core.paginator import Paginator
from df_user.check_login import check_login

# Create your views here.

def index(request):
	return render(request, 'df_goods/index.html')

def list_item(request, id):
	title = TypeInfo.objects.filter(id=id).values()
	context = {'title': list(title)[0]['ttype']}

	goods_ids = request.COOKIES.get('goods_ids', '')

	if goods_ids != '':
		result = []
		goods_idsl = goods_ids.split(',')

		for i in range(len(goods_idsl)):
			val = GoodsInfo.objects.filter(id=int(goods_idsl[i])).values()
			url = '/commodity/' + goods_idsl[i] +'/'
			result.append({'val':list(val)[0], 'url':url})

	else:
		result = ''

	context['result'] = result

	# return HttpResponse(context['result'][0]['gtitle'])
	return render(request, 'df_goods/list.html', context)

def list_items(request):
	get = request.GET
	page = get['page']
	type = get['type']

	type = int(type)
	list1 = GoodsInfo.objects.filter(gtype_id=type).values()

	p = Paginator(list(list1), 12)

	if page == '':
		page = '1'

	page = int(page)
	list2 = p.page(page)
	plist = p.page_range

	context = {'code':'查询成功', 'pageNum':page, 'pageCount':len(list(plist)), 'data':list(list2)}

	return JsonResponse(context)

@check_login
def commodity(request, id):
	good = GoodsInfo.objects.filter(id=id)[0]
	context = {
		'title': good.gtitle,
		'price': good.gprice,
		'src': good.gpic,
		'good_id': good.id,
	}

	goods_ids = request.COOKIES.get('goods_ids', '')
	goods_id = str(id)
	if goods_ids != '':
		goods_idsl = goods_ids.split(',')
		if goods_idsl.count(str(id)) >= 1:
			goods_idsl.remove(goods_id)
		goods_idsl.insert(0, goods_id)

		if len(goods_idsl) > 4:
			goods_idsl.pop()
		goods_ids = ','.join(goods_idsl)

	else:
		goods_ids = goods_id

	response = render(request, 'df_goods/commodityPage.html', context)
	response.set_cookie('goods_ids', goods_ids)

	return response

df_user/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from models import *
from hashlib import sha1

# Create your views here.


def register(request):
	return render(request, 'df_user/register.html')


def register_handle(request):
	post = request.POST
	uname = post.get('user_name')
	upwd = post.get('pwd')
	upwd2 = post.get('cpwd')
	uemail = post.get('email')

	if upwd != upwd2:
		return redirect('/user/register/')

	s1 = sha1()
	s1.update(upwd)
	upwd3 = s1.hexdigest()

	user = UserInfo()
	user.uname = uname
	user.upwd = upwd3
	user.uemail = uemail
	user.save()

	return redirect('/user/login')


def register_exist(request):
	uname = request.GET.get('uname')
	count = UserInfo.objects.filter(uname=uname).count()
	return JsonResponse({'count': count})


def login(request):
	if request.method == 'POST':
		req = request.POST
		username = req.get('username')
		pwd = req.get('pwd')

		s1 = sha1()
		s1.update(pwd)
		upwd = s1.hexdigest()

		context = {'data':False}
		try:
			data = list(UserInfo.objects.filter(uname=username).values())[0]['upwd']
			if data == upwd:
				context['data'] = True

		except Exception as e:
			print e
		
		return JsonResponse(context)

	return render(request, 'df_user/login.html', {'title':'登录'})

def logout(request):
	request.session.flush()
	response = HttpResponseRedirect('/')
	return redirect('/')

def site(request):

	if request.method == 'POST':
		uname = request.POST.get('username')
		allow = request.POST.get('allow')

		user = UserInfo.objects.filter(uname=uname)

		request.session['uname'] = user[0].id
		request.session.set_expiry(0)

		red = HttpResponseRedirect('/user/site/')

		if allow != 0:
			red.set_cookie('uname', uname)

		else:
			red.set_cookie('uname', '', max_age=-1)

		return red

	else:
		uname = request.COOKIES.get('uname')
		user = UserInfo.objects.filter(uname=uname)

		try:
			session = request.session['uname']

		except:
			session = ''

		if session == user[0].id:
			context = {'uname':uname, 'title':'用户中心'}
			return render(request, 'df_user/site.html', context)

		return redirect('/user/login/')	
	# return redirect(reverse('user:index'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{{title}} E-shop</title>
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/static/js/base.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/css/base.css">
	{%block head%}{%endblock head%}
</head>
<body>
		<div class="navbar navbar-default">
		<div class="container">
			<div class="row nav-font">
				<div class="col-lg-4 nav-wel-font">
					欢迎来到Eshop！
				</div>
				<div class="col-lg-offset-3 col-lg-4">
					<ul class="nav navbar-nav navbar-right">
						{% if request.session.uname|default:'' != '' %}
						<li class="nav-wel-font">欢迎您：<em>{{ request.COOKIES.uname }}</em></li>
						<li><a href="{%url 'user:logout'%}">退出</a></li>
						{%else%}
						<li><a href="{%url 'user:register'%}">注册</a></li>
						<li><a href="{%url 'user:login'%}">登录</a></li>
						{%endif%}
						<li><a href="{% url 'user:site' %}">用户中心</a></li>
						<li><a href="{% url 'cart:ucart' %}">我的购物车</a></li>
						<li><a href="#">我的订单</a></li>
					</ul>
				</div>
			</div>				
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="">
				<div class="navbar-brand">
					<a href="{% url 'goods:index' %}"><img src="/static/images/logo.PNG" alt="logo"></a>
				</div>

				<div class="col-lg-6 col-lg-offset-1">
					<div class="row search-box">
						<form action="" class="form-horizontal">
							<div class="form-group">
								<div class="input-group">
									<input type="text" name="" placeholder="热销中" class="form-control">
									<span class="input-group-btn">
										<button class="btn btn-default">
											<span class="glyphicon glyphicon-search"></span>
										</button>
									</span>
								</div>
							</div>
						</form>				
					</div>
					<div class="row hot-search">
						熱搜：
						<a href="#">百草味</a>
						<a href="#">唐诗三百首</a>
						<a href="#">周大福</a>
						<a href="#">童书5折抢</a>
						<a href="#">洁柔</a>
						<a href="#">尾品汇</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<nav class="navbar">
		<div class="row">
			<div class="container">
				<ul class="nav navbar-nav nav-tabs col-lg-12" style="border-bottom: none;">
					<li role="presentation" class="active" id="all_items">
						<a href="#"><label>全部商品</label><span class="caret"></span></a>
						<ul class="dropdown-menu slide_menu">
							<li><a href="#">图书、童书</a>
								<ul></ul>
							</li>
							<li><a href="#">电子书、网络文学</a>
								<ul></ul>
							</li>
							<li><a href="#">服饰、内衣</a>
								<ul></ul>
							</li>
							<li><a href="#">鞋靴、箱包</a>
								<ul></ul>
							</li>
							<li><a href="#">运动户外</a>
								<ul></ul>
							</li>
						</ul>
					</li>
					<li role="presentation" class=""><a href="{% url 'goods:list' 1 %}"><label>外套</label></a></li>
					<li role="presentation" class=""><a href="{% url 'goods:list' 2 %}"><label>羽绒服</label></a></li>
					<li role="presentation" class=""><a href="{% url 'goods:list' 3 %}"><label>鞋</label></a></li>
					<li role="presentation" class=""><a href="{% url 'goods:list' 4 %}"><label>裤子</label></a></li>
				</ul>
			</div>
			<div class="row slash"></div>
		</div>
	</nav>

	{%block body%}{%endblock body%}

	<div class="container-fluid footer">
		<div class="row">
			<div class="col-lg-3"></div>
			<div class="col-lg-1"><a href="#">公司简介</a></div>
			<div class="col-lg-1"><a href="#">诚聘英才</a></div>
			<div class="col-lg-1"><a href="#">网站联盟</a></div>
			<div class="col-lg-1"><a href="#">Eshop招商</a></div>
			<div class="col-lg-1"><a href="#">机构销售</a></div>
			<div class="col-lg-1"><a href="#">官方Blog</a></div>
			<div class="col-lg-3"></div>
		</div>
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
				<span>Copyright (C) Eshop 2004-2017, All Rights Reserved</span>
			</div>
		</div>
	</div>
</body>
</html>

templates/df_cart/cart.html
{% extends 'base.html' %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="/static/css/cart.css">
	<script type="text/javascript" src="/static/js/cart.js"></script>
{% endblock head %}

{% block body %}
	<div class="container">
		<div class="row">
			<table class="table table-self">
				<thead>
					<tr>
						<th>商品名称</th>
						<th>商品价格</th>
						<th>数量	</th>
						<th>小计</th>
						<th>操作</th>
					</tr>
				</thead>

				<tbody>
					{%for cart in carts%}
					<tr class="item" id="{{cart.id}}">
						<td class="item-pic">
							<input type="checkbox" name="item">
							<img src="{{cart.goods.gpic}}">
							<span>{{cart.goods.gtitle}}</span>
						</td>
						<td class="price">
							{{cart.goods.gprice}}
						</td>
						<td>
							<div class="input-group">
								<span class="input-group-btn">
									<button class="btn btn-default" id="plus">+</button>
								</span>
								<input type="text" class="form-control count" id="good_nums" value="{{cart.count}}">
								<span class="input-group-btn">
									<button class="btn btn-default" id="minus">-</button>
								</span>
							</div>
						</td>
						<td class="total">
							
						</td>
						<td>
							<a href="javascript:;" class="delete">删除</a>
						</td>
					</tr>
					{%endfor%}
				</tbody>
			</table>
			<div class="container">
				<div class="row text-right">
					<div class="col-lg-2 col-lg-offset-10">
						合计：￥<em id="aggregate"></em>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row text-right">
					<div class="col-xs-2 col-lg-offset-10">
						<input type="button" class="btn btn-primary form-control" value="结账">
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

templates/df_goods/commodityPage.html
{%extends 'base.html'%}

{%block head%}
	<script type="text/javascript" src="/static/js/commodity.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/commodityPage.css">
{%endblock head%}

{%block body%}
<div class="container">
	<div class="row">
		<h3 class="page-header">
			{{title}}
		</h3>
		<span hidden="hidden" id="good_id">{{good_id}}</span>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<img src="{{src}}" alt="" class="img-rounded">
		</div>
		<div class="col-lg-4 col-lg-offset-3" style="background-color:rgba(248, 248, 248, 0.7)">

			<div class="row page-header page-header-self">
				特惠价：￥<strong>{{price}}</strong>
			</div>

			<div class="row option" id="chooseSize">
				尺码：
				<button class="btn btn-default">S</button>
				<button class="btn btn-default">M</button>
				<button class="btn btn-default">L</button>
				<button class="btn btn-default">XL</button>
				<button class="btn btn-default">XXL</button>
			</div>

			<div class="row option">
				<div class="form-inline">
					数量：
					<select name="" id="goodsNum">
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
						<option value="6">6</option>
						<option value="7">7</option>
						<option value="8">8</option>
						<option value="9">9</option>
						<option value="10">10</option>
					</select>
					或
					<div class="input-group">
						<input type="text" class="form-control" placeholder="请输入需要的个数" id="goodsText">
						<span class="input-group-btn">
							<button class="btn btn-default" type="button">确定</button>
						</span>
					</div>
				</div>
			</div>

			<div class="row option">
				已选：<strong id="size"> </strong>，<strong id="num"> </strong>，<strong style="color:red;" id="result">现在有货</strong>
			</div>

			<div class="row option">
				<div class="input-group col-lg-offset-1">
					<div class="btn-group btn-group-self">
						<a href='#' role="button" class="btn btn-default btn-self">立即购买</a>
						<a href='javascript:;' role="button" class="btn btn-default btn-self" id="put_in_cart">加入购物车</a>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
{%endblock body%}

templates/df_user/login.html
{%extends 'base.html'%}

{%block head%}
	<script type="text/javascript" src="/static/js/logging.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/logging.css">
{%endblock head%}

{%block body%}
	<div class="container logging-input">
		<div class="row">
			<div class="col-lg-4">
				<blockquote>
					<p>勇者愤怒,抽刃向更强者;怯者愤怒,却抽刃向更弱者。</p>
					<footer>鲁迅</footer>
				</blockquote>
			</div>
			<div class="col-lg-4 col-lg-offset-3" style="background-color:rgba(248, 248, 248, 0.7)">
				<div class="page-header logging-header">
					用户登录
					<div class="logging">
						<a href="{%url 'user:register'%}">注册</a>
						<span class="glyphicon glyphicon glyphicon-menu-right"></span>
					</div>
				</div>
				
				<form action="{%url 'user:site'%}" class="form-horizontal" method="post">
					<div class="form-group">
						<lable class="col-lg-3 control-label">用户名:</lable>
						<div class="col-lg-9">
							<input type="text" class="form-control" id="username" name="username" placeholder="请输入账号" autocomplete="false">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<lable class="col-lg-3 control-label">密码:</lable>
						<div class="col-lg-9">
							<input type="password" class="form-control" id="pwd" name="pwd" value='' placeholder="请输入密码" autocomplete="false">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group"">
						<div class="checkbox col-lg-offset-3 col-lg-4">
							<label>
								<input type="checkbox" checked="checked" name="allow" id="allow">记住我
							</label>
						</div>
						<div class="col-lg-offset-9 forget">
							<a href="">忘记密码</a>
						</div>
					</div>
					<div class="form-group">
						<div class="col-lg-offset-2 col-lg-8">
							<input type="submit" class="btn btn-primary btn-block" value="提交">
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
{%endblock body%}

templates/df_user/register.html
{%extends 'base.html'%}

{%block head%}
	<script type="text/javascript" src="/static/js/register.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/register.css">
{%endblock head%}

{%block body%}
	<div class="container register-input">
		<div class="row">
			<div class="col-lg-4">
				<img src="/static/images/luxun.jpg" alt="鲁迅" class="">
			</div>
			<div class="col-lg-4 col-lg-offset-3" style="background-color:rgba(248, 248, 248, 0.7)">
				<div class="page-header register-header">
					用户注册
					<div class="register-logging">
						<a href="{%url 'user:login'%}">登录<span class="glyphicon glyphicon glyphicon-menu-right"></span></a>
					</div>
				</div>

				<form action="{%url 'user:register_handle'%}" class="form-horizontal" method="post">				<div class="form-group">
						<lable class="col-lg-3 control-label">用户名:</lable>
						<div class="col-lg-9">
							<input type="text" class="form-control" id="user_name" name="user_name">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<lable class="col-lg-3 control-label">密码:</lable>
						<div class="col-lg-9">
							<input type="password" class="form-control" id="pwd" name="pwd">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<lable class="col-lg-3 control-label">确认密码:</lable>
						<div class="col-lg-9">
							<input type="password" class="form-control" id="cpwd" name="cpwd">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<lable class="col-lg-3 control-label">邮箱:</lable>
						<div class="col-lg-9">
							<input type="text" class="form-control" id="email" name="email">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<div for="" class="col-lg-offset-3 col-lg-9">
							<div class="checkbox">
								<label>
									<input type="checkbox" checked="checked" name="allow" id="allow">同意“Eshop用户使用协议”
								</label>
							</div>
							<span class="error_tip error_tip2">请同意本协议</span>
						</div>
					</div>
					<div class="form-group">
						<div class="col-lg-offset-2 col-lg-8">
							<input type="submit" class="btn btn-primary btn-block" value="提交">
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
{%endblock body%}

templates/df_user/site.html
{%extends 'base.html'%}

{%block head%}
<link rel="stylesheet" href="/static/css/site.css">
{%endblock head%}

{%block body%}
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<h3>用户中心</h3>
				<div class="list-group">
				  <a href="#" class="list-group-item active">个人信息</a>
				  <a href="#" class="list-group-item">全部订单</a>
				  <a href="#" class="list-group-item">收货地址</a>
				</div>
			</div>
			<div class="col-lg-8 col-lg-offset-1">
				<h3 class="text-right">基本信息</h3>
				<div class="row">
					<div class="col-lg-8">
						<table class="table table-condensed">
							<tbody>
								<tr>
									<td>用户名：</td>
									<td>{{uname}}</td>
								</tr>
								<tr>
									<td>收货地址：</td>
									<td>sfadsf</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="col-lg-4">
						<img src=".\static\images\luxun.jpg" alt="">
					</div>
				</div>
			</div>
		</div>
	</div>
{%endblock body%}

templates/version-1/df_user/login.html
{%extends 'base.html'%}

{%block head%}
	<script type="text/javascript" src="/static/js/logging.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/logging.css">
{%endblock head%}

{%block body%}
	<div class="container logging-input">
		<div class="row">
			<div class="col-lg-4">
				<blockquote>
					<p>勇者愤怒,抽刃向更强者;怯者愤怒,却抽刃向更弱者。</p>
					<footer>鲁迅</footer>
				</blockquote>
			</div>
			<div class="col-lg-4 col-lg-offset-3" style="background-color:rgba(248, 248, 248, 0.7)">
				<div class="page-header logging-header">
					用户登录
					<div class="logging">
						<a href="{%url 'user:register'%}">注册</a>
						<span class="glyphicon glyphicon glyphicon-menu-right"></span>
					</div>
				</div>
				
				<form action="#" class="form-horizontal">
					<div class="form-group">
						<lable class="col-lg-3 control-label">用户名:</lable>
						<div class="col-lg-9">
							<input type="text" class="form-control" id="username" name="username">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<lable class="col-lg-3 control-label">密码:</lable>
						<div class="col-lg-9">
							<input type="password" class="form-control" id="pwd" name="pwd">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group"">
						<div class="checkbox col-lg-offset-3 col-lg-4">
							<label>
								<input type="checkbox" checked="checked" name="allow" id="allow">记住我
							</label>
						</div>
						<div class="col-lg-offset-9 forget">
							<a href="">忘记密码</a>
						</div>
					</div>
					<div class="form-group">
						<div class="col-lg-offset-2 col-lg-8">
							<input type="submit" class="btn btn-primary btn-block" value="提交">
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
{%endblock body%}

templates/version-1/df_user/register.html
{%extends 'base.html'%}

{%block head%}
	<script type="text/javascript" src="/static/js/register.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/register.css">
{%endblock head%}

{%block body%}
	<div class="container register-input">
		<div class="row">
			<div class="col-lg-4">
				<img src="/static/images/luxun.jpg" alt="鲁迅" class="">
			</div>
			<div class="col-lg-4 col-lg-offset-3" style="background-color:rgba(248, 248, 248, 0.7)">
				<div class="page-header register-header">
					用户注册
					<div class="register-logging">
						<a href="{%url 'user:login'%}">登录<span class="glyphicon glyphicon glyphicon-menu-right"></span></a>
					</div>
				</div>

				<form action="{%url 'user:register_handle'%}" class="form-horizontal" method="post">
					<div class="form-group">
						<lable class="col-lg-3 control-label">用户名:</lable>
						<div class="col-lg-9">
							<input type="text" class="form-control" id="user_name" name="user_name">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<lable class="col-lg-3 control-label">密码:</lable>
						<div class="col-lg-9">
							<input type="password" class="form-control" id="pwd" name="pwd">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<lable class="col-lg-3 control-label">确认密码:</lable>
						<div class="col-lg-9">
							<input type="password" class="form-control" id="cpwd" name="cpwd">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<lable class="col-lg-3 control-label">邮箱:</lable>
						<div class="col-lg-9">
							<input type="text" class="form-control" id="email" name="email">
							<span class="error_tip">提示信息</span>
						</div>
					</div>
					<div class="form-group">
						<div for="" class="col-lg-offset-3 col-lg-9">
							<div class="checkbox">
								<label>
									<input type="checkbox" checked="checked" name="allow" id="allow">同意“Eshop用户使用协议”
								</label>
							</div>
							<span class="error_tip error_tip2">请同意本协议</span>
						</div>
					</div>
					<div class="form-group">
						<div class="col-lg-offset-2 col-lg-8">
							<input type="submit" class="btn btn-primary btn-block" value="提交">
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
{%endblock body%}